const {chromium}=require('C:/Users/tanwa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {randomUUID}=require('node:crypto');
const base=process.env.QA_URL||'http://127.0.0.1:3001';
const folder='artifacts/visual-qa';
const sessions=[];
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'C:/Users/tanwa/AppData/Local/ms-playwright/chromium-1223/chrome-win64/chrome.exe'});
 try{
  const context=await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir:folder+'/analytics-video'},userAgent:'Mozilla/5.0 Chrome/130.0.0.0 Safari/537.36'});
  await context.addInitScript(()=>sessionStorage.setItem('portfolio_session','836e65ca-fca3-4f65-a128-bd4b01e72ac5'));
  sessions.push('836e65ca-fca3-4f65-a128-bd4b01e72ac5');
  const page=await context.newPage();
  await page.route('**/card.glb',async route=>{await new Promise(r=>setTimeout(r,2500));await route.continue();});
  await page.goto(base);
  await page.locator('dialog[open]').waitFor();
  await page.waitForTimeout(350);
  await page.screenshot({path:folder+'/analytics-loader.png'});
  await page.locator('dialog[open]').waitFor({state:'hidden',timeout:15000});
  assert.equal(await page.locator('h1').innerText(),'Tan Wai Ken.');
  await page.locator('.live-traffic').scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>document.querySelector('.traffic-heading')?.textContent.includes('refreshes every'));
  await page.waitForFunction(()=>document.querySelector('.traffic-heading')?.textContent.includes('refreshes every'));
  await page.screenshot({path:folder+'/analytics-footer.png'});
  const api=context.request;
  assert.equal((await api.get(base+'/api/analytics/details')).status(),401);
  assert.equal((await api.get(base+'/api/analytics/stream')).status(),401);
  const headers={Origin:base,'Content-Type':'application/json'};
  assert.equal((await api.post(base+'/api/analytics/collect',{headers,data:'null'})).status(),400);
  assert.equal((await api.post(base+'/api/analytics/collect',{headers:{...headers,Origin:'https://foreign.example'},data:{}})).status(),403);
  const before=(await (await api.get(base+'/api/analytics/summary')).json()).data;
  const session=randomUUID();sessions.push(session);
  const view={id:randomUUID(),session,kind:'view',referrer:'https://qa.example/private?secret=discard'};
  for(let i=0;i<2;i++)assert.equal((await api.post(base+'/api/analytics/collect',{headers,data:view})).status(),204);
  const after=(await (await api.get(base+'/api/analytics/summary')).json()).data;
  assert.equal(after.views,before.views+1);assert.ok(!('countries' in after));
  await api.post(base+'/api/analytics/collect',{headers:{...headers,DNT:'1'},data:{...view,id:randomUUID()}});
  assert.equal((await (await api.get(base+'/api/analytics/summary')).json()).data.views,after.views);
  await page.goto(base+'/analytics');
  await page.getByLabel('Owner access key').fill(process.env.ANALYTICS_ADMIN_SECRET);
  await page.getByRole('button',{name:'Open notebook'}).click();
  await page.getByText('Live stream · checks every 5 seconds',{exact:true}).waitFor();
  const clicks=Number(await page.locator('.analytics-totals strong').nth(1).innerText());
  await api.post(base+'/api/analytics/collect',{headers,data:{id:randomUUID(),session,kind:'click',action:'linkedin'}});
  await page.waitForFunction(n=>Number(document.querySelectorAll('.analytics-totals strong')[1]?.textContent)===n+1,clicks);
  assert.ok((await page.locator('body').innerText()).includes('qa.example'));
  await page.screenshot({path:folder+'/analytics-dashboard.png',fullPage:true});
  await page.getByRole('button',{name:'Pause updates'}).click();
  await page.getByText('Updates paused',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Resume updates'}).click();
  await page.getByRole('button',{name:'Sign out'}).click();
  await page.getByLabel('Owner access key').waitFor();
  assert.equal((await api.get(base+'/api/analytics/details')).status(),401);
  await page.setViewportSize({width:390,height:844});
  await page.goto(base);
  await page.locator('dialog[open]').waitFor();
  await page.getByRole('button',{name:'Enter portfolio'}).click();
  await page.locator('.live-traffic').scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>document.querySelector('.traffic-heading')?.textContent.includes('refreshes every'));
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:folder+'/analytics-mobile.png'});
  await page.goto(base+'/analytics');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:folder+'/analytics-mobile-login.png'});
  await context.close();
  console.log('PASS loader, responsive footer/login, real writes, idempotency, origin, DNT, private routes, owner login, live SSE, pause/resume and logout');
 }finally{fs.writeFileSync(folder+'/analytics-qa-sessions.json',JSON.stringify(sessions));await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
