const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const root='C:/Users/tanwa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const {chromium}=require(root+'/playwright');const sharp=require(root+'/sharp');
const out=path.resolve('artifacts/visual-qa');const checks=[];
async function difference(a,b){const [x,y]=await Promise.all([sharp(a).raw().toBuffer(),sharp(b).raw().toBuffer()]);let changed=0;for(let i=0;i<x.length;i++)if(Math.abs(x[i]-y[i])>15)changed++;return changed/x.length;}
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Users/tanwa/AppData/Local/ms-playwright/chromium-1223/chrome-win64/chrome.exe'});
try {
 const context=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto((process.env.QA_URL || 'http://127.0.0.1:3000'));await page.waitForSelector('.lanyard-portrait[data-ready="true"]',{timeout:60000});await page.waitForTimeout(6000);
 const stage=page.locator('.lanyard-stage');const still=await stage.screenshot();await page.waitForTimeout(600);const idle=await difference(still,await stage.screenshot());assert.ok(idle<.005,'Reduced motion idle drift '+idle);
 await page.locator('.lanyard-flip').focus();await page.keyboard.press('Enter');await page.waitForTimeout(180);const swing=await difference(still,await stage.screenshot());assert.ok(swing>.005,'Keyboard must move actual model '+swing);
 checks.push({name:'Reduced motion is visually still; keyboard activation moves the rendered GLB',idlePixelDifference:idle,swingPixelDifference:swing});
 assert.deepEqual(errors,[]);await context.close();
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const mp=await mobile.newPage();await mp.goto((process.env.QA_URL || 'http://127.0.0.1:3000'));await mp.waitForSelector('.lanyard-portrait[data-ready="true"]',{timeout:60000});await mp.locator('.lanyard-stage').scrollIntoViewIfNeeded();await mp.waitForTimeout(2000);await mp.screenshot({path:path.join(out,'glb-mobile.png')});
 const box=await mp.locator('.lanyard-stage canvas').boundingBox();const client=await mobile.newCDPSession(mp);const pt={x:box.x+box.width/2,y:box.y+box.height*.55};
 await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[pt]});await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:pt.x+25,y:pt.y-15}]});await mp.waitForTimeout(250);assert.equal(await mp.locator('.lanyard-portrait').getAttribute('data-dragging'),'true');await mp.screenshot({path:path.join(out,'glb-touch-drag.png')});await client.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await mp.waitForTimeout(100);assert.equal(await mp.locator('.lanyard-portrait').getAttribute('data-dragging'),'false');checks.push({name:'Emulated touch drag and cancellation release the card'});await mobile.close();
 const fallback=await browser.newContext({viewport:{width:390,height:844}});const fp=await fallback.newPage();await fp.route('**/card.glb',r=>r.abort());await fp.goto((process.env.QA_URL || 'http://127.0.0.1:3000'));await fp.getByRole('button',{name:'Reload 3D card',exact:true}).waitFor();assert.equal(await fp.locator('.lanyard-portrait').getAttribute('data-ready'),'false');assert.equal(await fp.locator('.lanyard-fallback').count(),0);await fp.unroute('**/card.glb');await fp.getByRole('button',{name:'Reload 3D card',exact:true}).click();await fp.waitForSelector('.lanyard-portrait[data-ready="true"]',{timeout:60000});checks.push({name:'Failed model request shows a retry control; retry works without a fallback image'});await fallback.close();
 fs.writeFileSync(path.join(out,'glb-report.json'),JSON.stringify({status:'PASS',checks},null,2));console.log(JSON.stringify(checks,null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
